# Pin npm packages by running ./bin/importmap

pin "application", preload: true
pin "genius-lyrics-api", to: "https://ga.jspm.io/npm:genius-lyrics-api@3.2.0/index.js"
pin "#lib/adapters/http.js", to: "https://ga.jspm.io/npm:axios@0.21.4/lib/adapters/xhr.js"
pin "axios", to: "https://ga.jspm.io/npm:axios@0.21.4/index.js"
pin "boolbase", to: "https://ga.jspm.io/npm:boolbase@1.0.0/index.js"
pin "cheerio-without-node-native", to: "https://ga.jspm.io/npm:cheerio-without-node-native@0.20.2/index.js"
pin "css-select", to: "https://ga.jspm.io/npm:css-select@1.2.0/index.js"
pin "css-what", to: "https://ga.jspm.io/npm:css-what@2.1.3/index.js"
pin "dom-serializer", to: "https://ga.jspm.io/npm:dom-serializer@0.1.1/index.js"
pin "domelementtype", to: "https://ga.jspm.io/npm:domelementtype@1.3.1/index.js"
pin "domhandler", to: "https://ga.jspm.io/npm:domhandler@2.4.2/index.js"
pin "domutils", to: "https://ga.jspm.io/npm:domutils@1.5.1/index.js"
pin "entities", to: "https://ga.jspm.io/npm:entities@1.1.2/index.js"
pin "entities/lib/decode_codepoint.js", to: "https://ga.jspm.io/npm:entities@1.1.2/lib/decode_codepoint.js"
pin "entities/maps/entities.json", to: "https://ga.jspm.io/npm:entities@1.1.2/maps/entities.json.js"
pin "entities/maps/legacy.json", to: "https://ga.jspm.io/npm:entities@1.1.2/maps/legacy.json.js"
pin "entities/maps/xml.json", to: "https://ga.jspm.io/npm:entities@1.1.2/maps/xml.json.js"
pin "eventemitter2", to: "https://ga.jspm.io/npm:eventemitter2@1.0.5/lib/eventemitter2.js"
pin "htmlparser2-without-node-native", to: "https://ga.jspm.io/npm:htmlparser2-without-node-native@3.9.2/lib/index.js"
pin "inherits", to: "https://ga.jspm.io/npm:inherits@2.0.4/inherits_browser.js"
pin "lodash", to: "https://ga.jspm.io/npm:lodash@4.17.21/lodash.js"
pin "nth-check", to: "https://ga.jspm.io/npm:nth-check@1.0.2/index.js"
pin "process", to: "https://ga.jspm.io/npm:@jspm/core@2.0.0-beta.19/nodelibs/browser/process-production.js"
